services:
  mysql:
    image: mysql:latest
    container_name: my_mysql
    ports:
      - "3666:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
